apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ignite-app
  labels:
    app: k8s-ignite-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-ignite-app
  template:
    metadata:
      labels:
        app: k8s-ignite-app
    spec:
      containers:
      - name: k8s-ignite-app
        image: ignite-k8s-asp
        imagePullPolicy: Never
        ports:
        - containerPort: 80
