version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: whatsnew-postgres
    ports:
      - "6432:5432"
    environment:
      POSTGRES_PASSWORD: P@ssword
    command: ["postgres", "-c", "log_statement=all"]